version: "3"
services:
  bot:
    container_name: bot
    build:
      context: ./app
    environment:
      URL: ${URL}
      TOKEN: ${TOKEN}
      MONGO_CONNECTION_STRING: ${MONGO_CONNECTION_STRING}
    ports:
      - 5000:5000
  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    stdin_open: true
    tty: true
    command: ngrok http bot:5000
    ports:
      - 443:443
      - 4040:4040
volumes:
  mongodbdata:
    driver: local