version: "3"
services:
  bot:
    container_name: bot
    build:
      context: ./app
    environment:
      - TOKEN
      - URL
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017
  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    stdin_open: true
    tty: true
    command: ngrok http bot:5000
    ports:
      - 443:443
      - 4040:4040
volumes:
  mongodbdata:
    driver: local